#!/usr/bin/env ruby
require 'yaml'
require 'erb'

exitStatus = 0

shape = YAML.load_file("shape.yaml")

Dir.chdir("shape") do
    template = ERB.new File.read("config.yaml.erb")
    File.write("config.yaml", template.result(binding)) 
end    

exit(exitStatus)
